#not parse it
main = "TOML STRING WITHOUT SECTION"
test = "second line of without section"

[time]

time = 2020-01-01T07:32:00+00:00 #random time

[database]

us .	er = 'root'#comment to delete
pass = "secret"
int = -214748364
port = 2147483649 #comment
en = false

[server]#connection

ip = "198.51.100.60"	#ip adress
key = 123
user = "redex2"
pass = "qwerty123"

[client]

port = 8888