#not parse it
main = "TOML STRING WITHOUT SECTION"
test = "second line of without section"

[time]

time = 2020-01-01T07:32:00+00:00 #random time

[database]

us .	er = 'root'#comment to delete
pass = "secret"
int = -214748364
port = 2147483649 #comment
en = false

[server]

ip = "198.51.100.60"	#ip adress
key = 123
user = "redex2"
pass = "qwerty123"
ipv6 = true
ipv4=false

[client]

port = 8888

[numbers]

bin = -0b1010
oct = -0o307216
hex = -0x3FC
ubin = 0b1010
uoct = 0o307216
uhex = 0x3FC